### ISSUE TITLE
[bug] RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by yangqing-yq** [philgras/video-head-tracker#7]
when run this command:
python vht/optimize_tracking.py --config your_config.ini --video path_to_video --data_path path_to_data

meet below issue:

[08/17 16:48:50 vht.util.video_to_dataset]: Extracting frame 0092
[08/17 16:48:50 vht.util.video_to_dataset]: Extracting frame 0093
[08/17 16:48:50 vht.util.video_to_dataset]: Extracting frame 0094
[08/17 16:48:50 vht.util.video_to_dataset]: Extracting frame 0095
[08/17 16:48:50 vht.util.video_to_dataset]: Extracting frame 0096
[08/17 16:48:50 vht.util.video_to_dataset]: Extracting frame 0097
[08/17 16:48:50 vht.util.video_to_dataset]: Extracting frame 0098
[08/17 16:48:50 vht.util.video_to_dataset]: Extracting frame 0099
Traceback (most recent call last):
  File "/home/qing/video-head-tracker/vht/optimize_tracking.py", line 51, in <module>
    main()
  File "/home/qing/video-head-tracker/vht/optimize_tracking.py", line 36, in main
    converter.annotate_landmarks()
  File "/home/qing/video-head-tracker/vht/util/video_to_dataset.py", line 235, in annotate_landmarks
    lmks_face, bboxes_faces = self._annotate_facial_landmarks()
  File "/home/qing/video-head-tracker/vht/util/video_to_dataset.py", line 119, in _annotate_facial_landmarks
    fa = face_alignment.FaceAlignment(
  File "/home/qing/anaconda3/envs/vht/lib/python3.9/site-packages/face_alignment/api.py", line 84, in __init__
    self.face_alignment_net = torch.jit.load(
  File "/home/qing/anaconda3/envs/vht/lib/python3.9/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by ohjarwa** [comment]
老哥 我也这样 一模一样的报错
hey bro I met the same problem as you pasted here

**Comment by yangqing-yq** [comment]
@philgras 
add my cuda version and pytorch vision here:
python 3.9
cudatoolkit 11.3.1
pytorch 1.11.0
pytorch-lightning 1.2.4
pytorch3d 0.7.0

`-------------------------------
tried another pytorch version - 1.10.1 is also same issue.

**Comment by yangqing-yq** [comment]
> 老哥 我也这样 一模一样的报错 hey bro I met the same problem as you pasted here

how about your pytorch version?

**Comment by ohjarwa** [comment]
> > 老哥 我也这样 一模一样的报错 hey bro I met the same problem as you pasted here
> 
> how about your pytorch version?

I made it.Here's my solution.
Delete the file in /users/.cache/torch/hub, rerun the script, keep your network connect well during  downloading the .pth file.
The error was most likely caused by the incomplete download of the pre-trained pth file.

**Comment by yangqing-yq** [comment]
> > > 老哥 我也这样 一模一样的报错 hey bro I met the same problem as you pasted here
> > 
> > 
> > how about your pytorch version?
> 
> I made it.Here's my solution. Delete the file in /users/.cache/torch/hub, rerun the script, keep your network connect well during downloading the .pth file. The error was most likely caused by the incomplete download of the pre-trained pth file.

it works!
